apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: absence-hpa-qa
  namespace: esprit-portail-entreprise-qa
  labels:
    app: portail-entreprise
    component: autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: absence

  
  minReplicas: 1    
  maxReplicas: 5  

  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80    
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70   

  
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  
      policies:
      - type: Percent
        value: 25          
        periodSeconds: 60
      - type: Pods
        value: 2          
        periodSeconds: 60
      selectPolicy: Min    

    scaleUp:
      stabilizationWindowSeconds: 60    
      policies:
      - type: Percent
        value: 50         
        periodSeconds: 120
      - type: Pods
        value: 1          
        periodSeconds: 120
      selectPolicy: Max    