apiVersion: v1
kind: Service
metadata:
  name: planning
  namespace: esprit-portail-entreprise-qa
  labels:
    app:  portail-entreprise
    portail-entreprise.service: planning
spec:    
  type: ClusterIP
  ports:
    - name: "http"
      port: 1925
      targetPort: 1925
  selector:
    app: portail-entreprise
    portail-entreprise.service: planning
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planning
  namespace: esprit-portail-entreprise-qa
  labels:
    app: portail-entreprise
    portail-entreprise.service: planning
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: portail-entreprise
      portail-entreprise.service: planning
  template:
    metadata:
      labels:
        app: portail-entreprise
        portail-entreprise.service: planning
    spec:
      nodeSelector:
        node-role: application-workload
      imagePullSecrets:
        - name: harbor-creds1
      serviceAccountName: esprit-app-sa
      initContainers:
      - name: vault-init
        image: hashicorp/vault:1.15.0
        command: 
        - vault
        - agent
        - -config=/vault/config/esprit-agent.hcl
        - -exit-after-auth
        env:
        - name: VAULT_ADDR
          value: "http://vault.vault.svc.cluster.local:8200"
        volumeMounts:
        - name: vault-config-esprit
          mountPath: /vault/config
        - name: vault-secrets
          mountPath: /vault/secrets 
      containers:
      - name: portail-planning
        image: harbor.pixelslabs.com/projetesprit/esprit-portail-entreprise_planning:v1.1.0-qa
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: dev
          - name: TZ
            value: "Africa/Tunis"
          - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
            value: "health,info,metrics,prometheus"
          - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
            value: "true"
          - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
            value: "true"
        command:
        - sh
        - -c
        - |
          echo "Loading secrets from Vault..."
          if [ -f /vault/secrets/esprit.env ]; then
            set -a  
            . /vault/secrets/esprit.env
            set +a
            echo "Secrets loaded successfully!"
          else
            echo "ERROR: No secrets file found!"
            exit 1
          fi
          exec java -cp "opt/app:opt/app/lib/*" com.dsi.planificationms.PlanificationMsApplication
        volumeMounts:
        - name: vault-secrets
          mountPath: /vault/secrets
          readOnly: true
        ports:
        - containerPort: 1925
        resources:
          requests:
            memory: "512Mi"  
            cpu: "150m"     
          limits:
            memory: "2900Mi"  
            cpu: "1500m"  
        readinessProbe:
          httpGet:
            path: /api/planif/actuator/health/readiness
            port: 1925
          initialDelaySeconds: 240
          periodSeconds: 30
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/planif/actuator/health/liveness
            port: 1925
          initialDelaySeconds: 240
          periodSeconds: 30
          failureThreshold: 3
      restartPolicy: Always
      volumes:
      - name: vault-config-esprit
        configMap:
          name: vault-config-esprit
      - name: vault-secrets
        emptyDir: {}
    
